accounts/urls.py
from django.urls import path
from . import views 

app_name = 'accounts'

urlpatterns = [
   path('signup', views.singup_view, name='signup'),
   path('login', views.login_view, name='login'),
   path('logout', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
  path('', views.article_list, name='article_list'),
  path('create', views.article_create, name='article_create'), 
  path('<slug>', views.article_detail, name='article_detail'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('articles.urls'))
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(unique=True)
    image = models.ImageField( blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE , default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def small_description(self):
        return self.body[:150] + '...'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.


def singup_view(request):
  if request.method == 'POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
          user = form.save()
          login(request, user)
          return redirect('accounts:login')
  else:
      form = UserCreationForm()
  return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
  if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)
      if form.is_valid():
          user = form.get_user()
          login(request, user)
          return redirect('accounts:login')
  else:
      form = AuthenticationForm()
  return render(request, 'accounts/login.html', {'form': form})



def logout_view(request):

      logout(request)
      return redirect('accounts:login')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required

# Create your views here.
def article_list(request):
  articles = Article.objects.all().order_by('-updated_at')

  context = {
    'articles': articles
  }
  
  return render(request, 'articles/article_list.html', context)

def article_detail(request, slug):
  
  article = Article.objects.get(slug=slug)

  context = {
    'article': article
  }
  
  return render(request, 'articles/article_detail.html', context)

def article_create(request):
  pass

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
ورود به سایت
{% endblock title %}

{% block content %} 
<div class="container">
         <div class="row">
            <div class="col-12">
               <div class="breadcrumb-wrap p-3 bg-white my-4 rounded">
                  <nav>
                     <ol class="d-flex">
                        <li><a href="#">خانه</a></li>
                        <li>صفحه ورود به سایت  </li>
                     </ol>
                  </nav>
               </div>
            </div>
         </div>
      </div>
      <section class="mb-5">
         <div class="container">
            <div class="row">
               <div class="col-12">
                  <div class="page-body bg-white rounded p-3">
                    <h2 class="mb-4">ورود به سایت</h2>
                    <form method="post" action="{% url 'accounts:login' %}">
                        {% csrf_token %}
                        {{ form }}
                    </br>
                        <button type="submit" class="btn btn-primary">ورود</button>
                    </form>

                  </div>
               </div>
            </div>
         </div>
      </section>
{% endblock content%}

templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block title %}
ورود به سایت
{% endblock title %}

{% block content %} 
<div class="container">
         <div class="row">
            <div class="col-12">
               <div class="breadcrumb-wrap p-3 bg-white my-4 rounded">
                  <nav>
                     <ol class="d-flex">
                        <li><a href="#">خانه</a></li>
                        <li>برگه خالی</li>
                     </ol>
                  </nav>
               </div>
            </div>
         </div>
      </div>
      <section class="mb-5">
         <div class="container">
            <div class="row">
               <div class="col-12">
                  <div class="page-body bg-white rounded p-3">
                    <h2 class="mb-4">ثبت نام در  سایت</h2>
                    <form method="post" action="{% url 'accounts:signup' %}">
                        {% csrf_token %}
                        {{ form }}
                    </br>
                        <button type="submit" class="btn btn-primary">ثبت نام</button>
                    </form>

                  </div>
               </div>
            </div>
         </div>
      </section>
{% endblock content%}

templates/articles/article_detail.html
{% extends "base.html" %}
{% load static %}



{% block title %}
{{ article.title }}
{% endblock title %}

{% block content %}
<section class="mb-5">
         <div class="container">
            <div class="row">
               <div class="col-lg-12">
                  <article>
                     <div class="section-top-single bg-white rounded p-3">
                        <div class="row">
                           <div class="col-md-7">
                              <figure>
                                 <img src="{{article.image.url}}" alt="" class="img-thumbnail d-table mx-auto">
                              </figure>
                           </div>
                           <div class="col-md-5">
                              <div class="border rounded p-3 mb-3">
                                 <h1 class="border-bottom"> {{article.title}} </h1>
                                 <ul class="detail-single d-flex">
                                    <li><i class="bi bi-instagram p-1"></i></li>
                                    <li><i class="bi bi-clock p-1"></i>&nbsp; {{ article.updated_at }} </li>
                                 </ul>
                                 <div class="text-start">
                                    
                                 </div>
                              </div>
                              <div class="border rounded p-3 single-excerpt-box">
                                 <span class="d-block py-2 text-info">خلاصه مطلب</span>
                                 <p class="m-0"> {{article.small_description}} </div>
                           </div>
                        </div>
                     </div>
                     <div class="content-single rounded bg-white p-3 mt-3">
                        <p> {{ article.body }} </p>
                        
                        
                        
                     </div>
                     
                  </article>
               </div>
               
            </div>
         </div>
      </section>

      {% endblock content %}

templates/articles/article_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
صفحه اصلی مقالات وبسایت
{% endblock title %}

{% block content %} 
<div class="container">
         <div class="row">
            <div class="col-12">
               <div class="breadcrumb-wrap p-3 bg-white my-4 rounded">
                  <nav>
                     <ol class="d-flex">
                        <li><a href="#">خانه</a></li>
                       
                     </ol>
                  </nav>
               </div>
            </div>
         </div>
      </div>
      
   {% include "articles/includes/posts_section.html" %}

{% endblock content%}

templates/articles/includes/hero_section.html
 {% load static %}
 

templates/articles/includes/posts_section.html
{% load static %}

 <section class="mb-5">
         <div class="container">
            <div class="row">
               

              {% for article in articles %}

               <div class="col-sm-6 col-md-6 col-lg-4 my-3">
                  <div class="blg-wrap bg-white pb-3">
                     <figure class="position-relative">
                     <img src="{{article.image.url}}" alt="" class="w-100">
                     <figcaption class="position-absolute w-100 h-100"><span class="blg-dt">{{article.updated_at}}</span></figcaption>
                     </figure class="position-relative">
                     <div class="px-3 py-1 text-start">
                        <span class="blg-cat-name d-inline-block bg-info py-1 px-2">مطالب روز</span>
                     </div>
                     <a href="{% url 'articles:article_detail' article.slug %}">
                        <h4 class="blg-title p-3 mx-5 text-dark border-bottom overflow-hidden">{{article.title}}</h4>
                     </a>
                     <div class="post-type d-flex p-3 pb-0">
                        <i class="bi bi-instagram d-inline-block text-info text-center"></i>
                        <span>مقاله اینستاگرام</span>
                     </div>
                     <p class="p-4 overflow-hidden"> {{article.small_description}} </div>
               </div>
              {% endfor %}



            </div>
         </div>
      </section>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap-icons.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.css' %}">
      <link rel="stylesheet" href="{% static 'assets/style.css' %}">
      <title> 
          {% block title %} 
          
          {% endblock title %}
      </title>
   </head>
   <body>
      <header>
         <div class="index-top position-relative w-100 bg-white">
            <div class="main-menu">
               <div class="container">
                  <div class="row">
                     <div class="col-md-2 col-3">
                        <img src="img/logo.png" alt="" height="30px" style="object-fit: contain;margin-top:18px;filter: grayscale(1);">
                     </div>
                     <div class="col-md-7 col-5 pt-2">
                        <nav class="navbar navbar-expand-lg navbar-light">
                           <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                              aria-expanded="false" aria-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span>
                           </button>
                           <div class="collapse navbar-collapse"
                              id="navbarSupportedContent">
                              <ul class="navbar-nav mb-2 mb-lg-0">
                                 <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="#">خانه</a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="#">مقالات</a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="#" tabindex="-1"
                                       aria-disabled="true">تماس با ما</a>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="#" tabindex="-1"
                                       aria-disabled="true">درباره</a>
                                 </li>
                                 <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                                       role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    دسته بندی ها
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                       <li><a class="dropdown-item" href="#">مجله فرهنگی</a></li>
                                       <li><a class="dropdown-item" href="#">مطالب ویدئویی</a></li>
                                       <li>
                                          <hr class="dropdown-divider">
                                       </li>
                                       <li><a class="dropdown-item" href="#">ارسالی مخاطبین</a></li>
                                    </ul>
                                 </li>
                              </ul>
                           </div>
                        </nav>
                     </div>
                     <div class="col-md-3 col-4 text-start">
                        <div class="top-account">
                           <a href="#" class="text-dark"><i class="bi bi-person"></i></a>
                           <a href="#" class="text-dark"><i class="bi bi-gem"></i></a>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </header>
      
        {% block content %}
        
        {% endblock content %}

      <footer class="bg-white py-4 text-center">
         <div class="container">
            <div class="row">
               <div class="col-12">
                  <ul class="d-flex justify-content-center social-bx">
                     <li class="p-2 m-1"><a href="#"><i class="bi bi-instagram"></i></a></li>
                     <li class="p-2 m-1"><a href="#"><i class="bi bi-twitter"></i></a></li>
                     <li class="p-2 m-1"><a href="#"><i class="bi bi-facebook"></i></a></li>
                  </ul>
               </div>
               <div class="col-12">
                  <p>وبلاگ اموزشی ما</p>
                  <p class="mb-0">&copy; حقوق انتشار برای مجموعه محفوظ است</p>
               </div>
            </div>
         </div>
      </footer>
      <div class="scroll_top">
         <span class="btn btn-info text-center text-light">
         <i class="bi bi-arrow-up"></i>
         </span>
      </div>
      <script src='{% static "assets/js/jQuery.js" %}'></script>
      <script src='{% static "assets/js/popper.js" %}'></script>
      <script src='{% static "assets/js/bootstrap.js" %}'></script>
      <script src='{% static "assets/js/owl.carousel.js" %}'></script>
      <script src='{% static "assets/js/index.js" %}'></script>
      
   </body>
</html>